(require 'onlyu-locale-settings)
(add-to-list 'load-path "emacs/externals/erlang-mode")
(add-to-list 'load-path "~/emacs/vendor/distel/elisp")
(require 'distel)
(distel-setup)
(add-to-list 'auto-mode-alist '("\\.erl$" . erlang-mode))
(provide 'onlyu-erlang)
