/* this file automatically generated by the Makefile */
#define COMPILER "gcc44"
#define OPTIMIZE "-pipe -march=native -fprefetch-loop-arrays -DFD_SETSIZE=10000 -Wall -D_THREAD_SAFE -fomit-frame-pointer -fstrength-reduce -g "
#define CFLAGS   "-g -Werror -Iinclude/ -I./ -I/usr/local/include  -Igrammar/  -Ilib/"
#define OBJDIR   "obj"
#define GAME_MODULE 1
