#ifndef _FS_STATIC_RPC_ID_H_
#define _FS_STATIC_RPC_ID_H_


/*
#define RPC_CLIENT_UPDATE_PTO 1
#define RPC_SERVER_VERSION 2
#define RPC_CLIENT_VERSION_RETURN 3
*/

//手动指定协议begin
//服务端给客户端发协议文件的内容
#define RPC_SERVER_VERSION 2
//客户端给服务端发客户端的引擎版本和客户端脚本版本，外加协议文件的md5内容
#define RPC_CLIENT_UPDATE_PTO 1
#define RPC_CLIENT_VERSION_RETURN 3

// SCENE
#define RPC_CLIENT_ADD_NPC 16
#define RPC_CLIENT_ADD_PLAYER 17
#define RPC_CLIENT_ADD_SUMMON 18
#define RPC_CLIENT_CHAR_ADD_EFFECT 19
#define RPC_CLIENT_CHAR_DEL_EFFECT 20
#define RPC_CLIENT_CHAR_NAME_TITLE_COLOR 21
#define RPC_CLIENT_CHAR_SET_HEAD_ADDON 22
#define RPC_CLIENT_CHAR_STATUS 23
#define RPC_CLIENT_CHAR_WARFOG_PROP 24
//#define RPC_CLIENT_DEL_NPC 25
//#define RPC_CLIENT_DEL_PLAYER 26
//#define RPC_CLIENT_DEL_SUMMON 27
#define RPC_CLIENT_ENTER_SCENE 28
#define RPC_CLIENT_GOTO 29
#define RPC_CLIENT_MOVE 30
#define RPC_CLIENT_RESET_WARFOG 31
#define RPC_CLIENT_SCENE_OBJECT_SHOW 32
#define RPC_CLIENT_SCENE_PROP 33
#define RPC_CLIENT_TEAM 34
#define RPC_CLIENT_WALK 35
#define RPC_SERVER_CLICK_NPC 36
#define RPC_SERVER_MOVE 37
#define RPC_SERVER_MOVE_TEST 38
// 摊位信息
#define RPC_CLIENT_STALL_INFO 39 
// NPC跟随信息
#define RPC_CLIENT_CHAR_FOLLOW 40

#define RPC_CLIENT_DEL_CHAR 41
#define RPC_CLIENT_DEL_CHARS 42

#define RPC_CLIENT_CHAR_DIR 43
#define RPC_CLIENT_CHAR_PARTS_EQUIP_PROP 44
// ----------------------


// LOGIN
#define RPC_SERVER_VERIFY  60
#define RPC_SERVER_PPC_INPUT 61
#define RPC_SERVER_REQUEST_LOGIN_KEY 62
#define RPC_SERVER_USE_LOGIN_KEY 63
#define RPC_SERVER_LOGIN 64
#define RPC_SERVER_DEL_UID 65
#define RPC_SERVER_NEW_UID 66
//yy openid
#define RPC_SERVER_YY_OPENID_SESSIONINFO 67
#define RPC_SERVER_YY_OPENID_SESSIONKEY 68
//#define RPC_CLIENT_YY_OPENID_SESSIONKEY 69
//#define RPC_CLIENT_VERIFY_EXT_METHOD 70
// FAST_REGISTER
#define RPC_SERVER_FAST_REGISTER 71
#define RPC_CLIENT_FAST_REGISTER_RETURN 72


// OTHER
#define RPC_SERVER_UPDATE_PLAYER 80
#define RPC_CLIENT_SCENE_BLOCK 81
#define RPC_CLIENT_PLAYER_INFO 82
//防外挂
#define RPC_SERVER_PTO_STATS_THRESHOLD 83

// 阵营
#define RPC_CLIENT_CHAR_FACTION 84

#endif // _FS_STATIC_RPC_ID_H_
